# Generated by Django 6.0.2 on 2026-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='disease',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='disease',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Disease Name'),
        ),
    ]
